name: Building and testing GUI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ########################################
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libgtk-3-dev libcairo2-dev libglib2.0-dev

    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: 1.19

    - name: Build the binary
      run: make build_gui

    - name: Installing golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Lint check
      run: BUILD_TAG=gtk make check

  ########################################
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Dependencies
      run: brew install gtk+3

    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: 1.19

    - name: Build the binary
      run: make build_gui

  ########################################
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - uses: msys2/setup-msys2@07aeda7763550b267746a772dcea5e5ac3340b36 # v2
      with:
        msystem: MINGW64
        update: true
        install:
          git
          make
          glib2-devel
          mingw-w64-x86_64-go
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config

    - name: Print go version
      run: go version

    - name: Build the binary
      run: |
        # This fixes a bug in pkgconfig: invalid flag in pkg-config --libs: -Wl,-luuid
        sed -i -e 's/-Wl,-luuid/-luuid/g' /mingw64/lib/pkgconfig/gdk-3.0.pc
        make build_gui
