name: Releaser

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  ########################################
  build-cli:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ubuntu-latest

    # Defining outputs for jobs
    # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    outputs:
      checksums: ${{ steps.calc_checksums.outputs.checksums }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install zip

    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: 1.19

    - name: Create release files
      run: bash ./.github/releasers/releaser_cli.sh

    # Multiline strings in GitHub actions
    # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
    - name: Calculate sha256sum
      id: calc_checksums
      run: |
        set -e
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "checksums<<$EOF"                          >> "$GITHUB_OUTPUT"
        echo "$(sha256sum pactus-*.zip pactus-*tar.gz)" >> "$GITHUB_OUTPUT"
        echo "$EOF"                                     >> "$GITHUB_OUTPUT"

    - name: Publish
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        files: |
          pactus-*.zip
          pactus-*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  build-gui-linux:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ubuntu-latest

    outputs:
      checksums: ${{ steps.calc_checksums.outputs.checksums }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libgtk-3-dev libcairo2-dev libglib2.0-dev

    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: 1.19

    - name: Create release files
      run: bash ./.github/releasers/releaser_gui_linux.sh

    - name: Calculate sha256sum
      id: calc_checksums
      run: |
        set -e
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "checksums<<$EOF"             >> "$GITHUB_OUTPUT"
        echo "$(sha256sum pactus-*tar.gz)" >> "$GITHUB_OUTPUT"
        echo "$EOF"                        >> "$GITHUB_OUTPUT"

    - name: Publish
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        files: pactus-*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  build-gui-macos:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: macos-latest

    outputs:
      checksums: ${{ steps.calc_checksums.outputs.checksums }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Install Dependencies
      run: brew install gtk+3 librsvg create-dmg coreutils

    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: 1.19

    - name: Create release files
      run: bash ./.github/releasers/releaser_gui_macos.sh

    - name: Calculate sha256sum
      id: calc_checksums
      run: |
        set -e
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "checksums<<$EOF"                          >> "$GITHUB_OUTPUT"
        echo "$(sha256sum pactus-*.dmg pactus-*tar.gz)" >> "$GITHUB_OUTPUT"
        echo "$EOF"                                     >> "$GITHUB_OUTPUT"

    - name: Publish
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        files: |
          pactus-*.dmg
          pactus-*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  build-gui-windows:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: windows-latest

    outputs:
      checksums: ${{ steps.calc_checksums.outputs.checksums }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - uses: msys2/setup-msys2@07aeda7763550b267746a772dcea5e5ac3340b36 # v2
      with:
        msystem: MINGW64
        update: true
        install:
          git
          make
          p7zip
          glib2-devel
          mingw-w64-x86_64-go
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config

    - name: Create release files
      run: bash ./.github/releasers/releaser_gui_windows.sh

    - name: Calculate sha256sum
      id: calc_checksums
      run: |
        set -e
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "checksums<<$EOF"                                 >> "$GITHUB_OUTPUT"
        echo "$(sha256sum pactus-*.zip pactus-*installer.exe)" >> "$GITHUB_OUTPUT"
        echo "$EOF"                                            >> "$GITHUB_OUTPUT"

    - name: Publish
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        files: |
          pactus-*.zip
          pactus-*installer.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  checksums:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    needs: [build-cli, build-gui-linux, build-gui-macos, build-gui-windows]
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Create SHA256SUMS file
      run: |
        echo "${{ needs.build-cli.outputs.checksums }}" >> SHA256SUMS
        echo "${{ needs.build-gui-linux.outputs.checksums }}" >> SHA256SUMS
        echo "${{ needs.build-gui-macos.outputs.checksums }}" >> SHA256SUMS
        echo "${{ needs.build-gui-windows.outputs.checksums }}" >> SHA256SUMS
    - name: Publish
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        files: SHA256SUMS
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  downloader:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    needs: [checksums]
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit

    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Create Downloader file
      run: |
        VERSION="$(echo `git -C . describe --abbrev=0 --tags` | sed 's/^.//')" # "v1.2.3" -> "1.2.3"
        echo ${VERSION}
        sed -i "s/__VERSION__/${VERSION}/g" .github/releasers/pactus_downloader.sh

    - name: Publish
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        files: .github/releasers/pactus_downloader.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
